const MAKE = ["Acura", "Alfa Romeo", "Aston Martin", "Audi", "Bentley", "BMW", "Buick", "Cadillac", "Chevrolet", "Chrysler", "Dodge", "FIAT", "Ford", "Genesis", "GMC", "Honda", "Hyundai", "INFINITI", "Jaguar", "Jeep", "Kia", "Lamborghini", "Land Rover", "Lexus", "Lincoln", "Lotus", "Maserati", "Mazda", "McLaren", "Mercedes-Benz", "MINI", "Mitsubishi", "Nissan", "Polestar", "Porsche", "Ram", "Rolls-Royce", "Subaru", "Tesla", "Toyota", "Volkswagen", "Volvo"]

const MODEL = [
  "1",
  "124 Spider",
  "1500",
  "1500 Classic",
  "2 Series",
  "2 Series Gran Coupe",
  "2500",
  "3",
  "3 Series",
  "300",
  "3500",
  "370Z",
  "4 Series",
  "4 Series Gran Coupe",
  "4C",
  "4Runner",
  "5 Series",
  "500L",
  "500X", 
  "570S",
  "570S Spider",
  "6",
  "600LT Spider",
  "7 Series",
  "718 Boxster",
  "718 Cayman",
  "720S",
  "720S Spider",
  "8 Series",
  "8 Series Gran Coupe",
  "86",
  "911",
  "A-Class",
  "A3",
  "A4",
  "A4 allroad",
  "A5",
  "A6",
  "A6 allroad",
  "A7",
  "A8",
  "Acadia",
  "Accent",
  "Accord",
  "Accord Hybrid",
  "ALPINA B7",
  "Altima",
  "AMG GT",
  "Armada",
  "Arteon",
  "Ascent",
  "Atlas",
  "Atlas Cross Sport",
  "Avalon",
  "Avalon Hybrid",
  "Aventador",
  "Aviator",
  "Bentayga",
  "Blazer" ,
  "Bolt EV",
  "BRZ",
  "C-Class",
  "C-HR",
  "Cadenza",
  "Camaro", 
  "Camry",
  "Camry Hybrid",
  "Canyon",
  "Cayenne",
  "Cayenne Coupe",
  "Challenger",
  "Charger",
  "Cherokee",
  "Civic",
  "CLA-Class",
  "Clarity",
  "CLS-Class",
  "Clubman",
  "Colorado",
  "Compass",
  "Continental",
  "Convertible",
  "Corolla",
  "Corolla Hatchback",
  "Corolla Hybrid",
  "Corsair", 
  "Corvette",
  "Countryman",
  "CR-V",
  "CR-V Hybrid",
  "Crosstrek",
  "CT4",
  "CT5",
  "CT6",
  "CT6-V", 
  "Cullinan",
  "CX-3",
  "CX-30",
  "CX-5",
  "CX-9"]



const BODIES = ["Sedan", "SUV", "Coupe", "Convertible", "Wagon", "Hatchback"]

const ENGINES = ["diesel", "electric", "gas", "hybrid", "mild hybrid"]

export const atrributesGroup = [MAKE, MODEL, BODIES, ENGINES ]